### PR TITLE
Add profile pictures for GitHub contributors

### PR DESCRIPTION
**Pull request by rettetdemdativ**
See #36

### CODE REVIEW

**Review by robaxelsen — APPROVED** [review]

**Comment by robaxelsen** [comment]
@calmandniceperson LGTM :+1: 

@DDCreationStudios what do you think?

**Comment by rettetdemdativ** [comment]
Accidentally committed here when I added Monika Schrenk. Reverted the change in case you're going to merge both pull requests (doesn't really matter if you just take the second one or both, I guess) so you don't have merge conflicts regarding that.

**Review by Createdd — CHANGES_REQUESTED** [review]
@robeerob 
We can dismiss this PR since I merged the other one, right? 
If yes, feel free to close the PR @robeerob

**Comment by robaxelsen** [comment]
@DDCreationStudios Yes, closing now.

**Pull request closed without merging**
