### PR TITLE
Sponsors

### PR DESCRIPTION
**Pull request by Frazer**
I added sponsor logos, and a link in the sponsors section to contact the organizers.

### CODE REVIEW

**Comment by Createdd** [comment]
Thanks a lot @Frazer! 

I was thinking about creating a whole section for the sponsors. Displaying all of them, and leaving room for future ones, in an own row. 
@robeerob  What are your thoughts on that?

**Comment by Frazer** [comment]
I thought I left room for 5 more.  Should be good for 5 more months 😛 

I made that section only 2/3 of the width of the page, trying to work with the 'program' section.

**Comment by robaxelsen** [comment]
Great initiative, and thanks for taking your time to contribute @Frazer.

@Frazer and @DDCreationStudios: I pushed a commit to the PR, in an attempt to improve the layout and "expand" the sponsor section to be more in line with Daniel's wish for a separate sponsor section (as opposed to part of the existing Programs/Goals/Sponsors row). Please review, and if it LGTY, I propose we merge this to master.

**Comment by Createdd** [comment]
Awesome guys! Thanks, I will take a look at it as soon as I have a little free time :)

**Pull request merged**
