### PR TITLE
Solution to issues #20 , #11 and #24

### PR DESCRIPTION
**Pull request by phbrasiliano**
I made one commit for each one of the issues. Both should correct those bugs. I can't say for sure because I couldn't find a way of testing it without hosting it as an website again.
Let me know if anything is wrong, it is the first time I'm contributing to a project.

### CODE REVIEW

**Comment by Createdd** [comment]
Hi @phbrasiliano ! Thanks a lot! I will have a look as soon as possible! When you take a look at the current Pull Requests you will see that issue #11 is already waiting for the approvement with PR #19 :)

**Comment by phbrasiliano** [comment]
oh, thanks for letting me know, I guess because they are on different commits, you can take the changes one by one right?

also, is there anywhere I can make suggestions? I would like to discuss about a favicon for the page.

**Comment by Createdd** [comment]
@phbrasiliano Yeah of course :) 
Yes, use the [issues section](https://github.com/FCCVienna/FCCVienna.github.io/issues) and just add your ideas ;)

**Comment by phbrasiliano** [comment]
I also added the favicon to the page in this pull request.
I tried cherry picking the commit and making a new pull request, but I had a bit of trouble. I hope it is fine, if  it is not I can try to do it correctly, just let me know.

**Comment by robaxelsen** [comment]
Solved conflicts. LGTM. Please review and merge if +1, @DDCreationStudios.

**Review by Createdd — APPROVED** [review]

**Pull request merged**
