### PR TITLE
Add profile pictures for contributors

### PR DESCRIPTION
**Pull request by robaxelsen**
To be used for PR related to #36.

### CODE REVIEW

**Comment by Createdd** [comment]
@robeerob  Have you asked all of those people for their confirmation (written) that we can use their pictures? Because in jurisdiction linking files with an absolute path is handled differently than uploading personal photos on our own platform.

**Comment by robaxelsen** [comment]
@DDCreationStudios good point. No I have not asked them. I propose we reduce the scope of this issue to only require dummy (license free) profile icons/graphics for the PR. That way we can add real pictures on a per contributor basis once/if they confirm. 

One thing to note, it would be nice to have circular profile pictures created by using square pictures but border-radius css property to add the circular effect.

**Comment by Createdd** [comment]
@robeerob 
I think it's easiest to simply link their github profile picture. No need for dummy pictures. Not quite sure what you mean by dummy pictures, but pictures that are not the contributors are just unneccessary and uglify our page. 
Maybe you can open a PR with an example with us two to lay a starting point for other contributors? 

Feel free to dismiss this PR #39  if it's not relevant anymore. :)

**Comment by robaxelsen** [comment]
@DDCreationStudios Ah, then I misunderstood your previous comment. With dummy picture I meant a generic graphical element to use as a placeholder when no actual picture exists for the person. Will dismiss this PR then :)

**Pull request closed without merging**
