### PR TITLE
card-hover tooltips

### PR DESCRIPTION
**Pull request by Otto-AA**
Adding a .card-hover class to the styles.css file and using this class in the index.html file. With this, one can hover a card and can read more information / click useful links.

Feel free to leave feedback on my changes (and on my github behaviour, as I'm fairly new to it ;)

### CODE REVIEW

**Comment by Createdd** [comment]
Great idea @Otto-AA! Looks good! :) 

Some things to consider: 
- there is already a hover class in the framework (http://materializecss.com/helpers.html)
- regarding design we maybe should adapt according to overall appearence, for example
  - change the background color to teal-like
  - change the color of the text and a-tags

@robeerob  What are your thoughts on that?
Maybe we can also review the changes together @ the next meetup? If that's of interest. :)

**Comment by Otto-AA** [comment]
@DDCreationStudios 
Thanks for the feedback!

If you mean the class ".hoverable", it's only for adding a shadow to the element, whereas mine is to show more content. I also tried it with tooltips (http://materializecss.com/dialogs.html) but I didn't manage to put clickable links there (The tooltip disappears when moving over it).

Regarding the design, I'll think more about it back at home...

**Comment by Otto-AA** [comment]
@DDCreationStudios 
To be honest, the white background seems pretty nice to me and I would go with it O.o
But do not hesitate to try out things on your own, maybe also adding a border to the .card-hover.
Currently you can also add the .teal class to it, but the arrow pointing up won't change its color, as it is defined via a border and not the background. But this can be changed if neccessary.

P.S. I have updated the styles.css file to be more crossbrowser. Only checked it in Firefox though, so feedback if it works in other browsers would be appreciated.

**Comment by Otto-AA** [comment]
Here is a Pen to mess around with this current version: https://codepen.io/A_A/pen/VzBWNV?editors=0100

**Comment by robaxelsen** [comment]
Love the look and feel of this, and it's a nice additional feature. Well done, @Otto-AA. Merged after reading the conversation, testing locally, and seeing that @DDCreationStudios +1 your last update.

**Pull request merged**
